server:
  port: 9003

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group-account
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: *
  datasource:
    url: jdbc:mysql://localhost:3306/banking_transaction?createDatabaseIfNotExist=true
    username: {cipher}d67fb8d46a8ae848f2db9afd66432ba5d7a74a63f0fad4408a4e09288a9934e2
    password: {cipher}d67fb8d46a8ae848f2db9afd66432ba5d7a74a63f0fad4408a4e09288a9934e2
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
    base-url: http://localhost:9411/zipkin
    sleuth:
      sampler:
        probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


